(ns roman.core-test
  (:require [clojure.test :refer :all]
            [roman.core :refer :all]))

(defn- random-roman [len]
  (->> (fn [] (rand-nth "MDCLXVI"))
       repeatedly
       (take len)
       (apply str)))

(deftest empty-string []
  (is (= nil (roman2arabic ""))))

(deftest single-numerals []
  (is (= 1000 (roman2arabic "M")))
  (is (= 500 (roman2arabic "D")))
  (is (= 100 (roman2arabic "C")))
  (is (= 50 (roman2arabic "L")))
  (is (= 10 (roman2arabic "X")))
  (is (= 5 (roman2arabic "V")))
  (is (= 1 (roman2arabic "I"))))

(deftest additive []
  (is (= 2000 (roman2arabic "MM")))
  (is (= 1500 (roman2arabic "MD")))
  (is (= 1100 (roman2arabic "MC")))
  (is (= 1050 (roman2arabic "ML")))
  (is (= 1010 (roman2arabic "MX")))
  (is (= 1005 (roman2arabic "MV")))
  (is (= 1001 (roman2arabic "MI"))))

(deftest additive-and-subtractive []
  (is (= 1999 (roman2arabic "MIM")))
  (is (= 1495 (roman2arabic "MVD")))
  (is (= 1090 (roman2arabic "MXC")))
  (is (= 1040 (roman2arabic "MXL")))
  (is (= 1005 (roman2arabic "MVX")))
  (is (= 1004 (roman2arabic "MIV")))
  (is (= 1000 (roman2arabic "IMI"))))

(deftest random-roman []
  (let [roman "IDDCILVCXCDMVMMCCLXIDDILMCMICIMVMCXVCMCVDLIVXCVIIXCLXXXDLMMDDVLMMLLVDVMDCLDCCXMLVXVLVIVIMVIMDMVVMCCMDICCLVLMLDMMXDCLIILICXILCXXDVDMMDVMXCVLVDMILVXMLDLMDDVDMIDLDVCLIMVLCVVLICCMXLXVLLXMICVIXVDDXDIMMDCLDVLCDIDMCLMLVMLIXDXCMMIMCDLDLMMCIDVVDLLLILIIDVIMLCLCCICMXCLIVCCDDVMIVVDVXCVXILILCDLCXIXVILDCCCIIIXLXXXVVLXDXLCXXDDCDCDIIMXIXCMXDXCCDLMXXIDCVIVVICCMDDDXLMVIVMVLMMDDMDLMDDMMVCXCCLVVCIXMLDIXDVCXVDMCMLIVCMMCMMCMXVDDLDCLILVLLVVCIDXXXVMMICDCXCXLIMLXCDMIIDCMLCXDXXLCMCLMDLLCMIDICCVXVIVDVIIVLILMDVDVXMDLXIMIICMMDMVIDMXXXMLVXILVMVCMDCIXMDVMXMXXIIVVXXLCCIXIXMDIXVILMILLLDCLVCDIMICLLILIDLIVCMLXLMDLIXIXDDLXMXDCIIIIXILMDMXCIMIXLCLCIXLLLDIDVIIVCMXVLVLIIICMLXXDCIXXDCVLXLVCIVVXDXCLCVMDILXLVMVMMXLIILLILIIMCVMXVLCLDMCCLVXLDMLILVXVCXVMDMDVMVMXMCIMVDDIMCXXMCICXVLIVXDLVXMCCXDXVDVVCVLIMIMICLVDLXCVXCMMLDCXMDVVVDDXIVMCDIMIVLXXLXXXLVILDDLILIIDVXDXXCMMLCMMCVICILMDVMLVVXIMXIXCDIMIDMLIVLVDVLCXXMLCDXDDDLMLXCXMIMDIVVXXLLXMMCVIDLDMMLCXVVMDXXDMXMXMXMDLDDIMLCDVMMVCIXDICVMXMCMXVVMLCCIXLVLLLDLXCIVIDCVDXIDCCXCMXMLDLXMIDMDMVIDMDC"]
    (is (= 1410 (roman2arabic roman)))))
