(ns roman.core-test
  (:require [clojure.test :refer :all]
            [clojure.math.combinatorics :refer [selections]]
            [roman.core :refer :all]))

(defn- random-roman [len]
  (->> (fn [] (rand-nth "MDCLXVI"))
       repeatedly
       (take len)
       (apply str)))

(defn- random-selections [len count]
  (let [selection-seq (map (partial apply str) (selections "MDCLXVI" len))]
    (->> (fn [] (rand-nth selection-seq))
         repeatedly
         (take count))))

(deftest empty-string []
  (is (= nil (roman2arabic ""))))

(deftest invalid-string []
  (is (= nil (roman2arabic "z")))
  (is (= nil (roman2arabic "Mz")))
  (is (= nil (roman2arabic "Dz")))
  (is (= nil (roman2arabic "pCz")))
  (is (= nil (roman2arabic "Lz")))
  (is (= nil (roman2arabic "Xz")))
  (is (= nil (roman2arabic "Vz")))
  (is (= nil (roman2arabic "sDz")))
  (is (= nil (roman2arabic "Izo"))))

(deftest single-numerals []
  (is (= 1000 (roman2arabic "M")))
  (is (= 500 (roman2arabic "D")))
  (is (= 100 (roman2arabic "C")))
  (is (= 50 (roman2arabic "L")))
  (is (= 10 (roman2arabic "X")))
  (is (= 5 (roman2arabic "V")))
  (is (= 1 (roman2arabic "I"))))

(deftest additive []
  (is (= 2000 (roman2arabic "MM")))
  (is (= 1500 (roman2arabic "MD")))
  (is (= 1100 (roman2arabic "MC")))
  (is (= 1050 (roman2arabic "ML")))
  (is (= 1010 (roman2arabic "MX")))
  (is (= 1005 (roman2arabic "MV")))
  (is (= 1001 (roman2arabic "MI"))))

(deftest additive-and-subtractive []
  (is (= 1999 (roman2arabic "MIM")))
  (is (= 1495 (roman2arabic "MVD")))
  (is (= 1090 (roman2arabic "MXC")))
  (is (= 1040 (roman2arabic "MXL")))
  (is (= 1005 (roman2arabic "MVX")))
  (is (= 1004 (roman2arabic "MIV")))
  (is (= 1000 (roman2arabic "IMI"))))

(deftest random-four-digits []
  (is (= 494 (roman2arabic "DIVM")))
  (is (= 46 (roman2arabic "VLCI")))
  (is (= 1985 (roman2arabic "VMXM")))
  (is (= 4 (roman2arabic "IIII")))
  (is (= 1049 (roman2arabic "IMLC")))
  (is (= 499 (roman2arabic "XIDX")))
  (is (= 540 (roman2arabic "XLDC")))
  (is (= 0 (roman2arabic "MXMX")))
  (is (= 904 (roman2arabic "CMIV")))
  (is (= 961 (roman2arabic "LMXI")))
  (is (= 499 (roman2arabic "VDIV")))
  (is (= 495 (roman2arabic "XVDX")))
  (is (= 1455 (roman2arabic "LMDV")))
  (is (= 1895 (roman2arabic "VCMM")))
  (is (= 1150 (roman2arabic "MLLL")))
  (is (= 994 (roman2arabic "DIVD")))
  (is (= 489 (roman2arabic "VVID")))
  (is (= 103 (roman2arabic "ICIV")))
  (is (= 1899 (roman2arabic "ICMM")))
  (is (= 2999 (roman2arabic "MMIM")))
  (is (= 891 (roman2arabic "XCMI")))
  (is (= 602 (roman2arabic "DCII")))
  (is (= 480 (roman2arabic "VVXD")))
  (is (= 1499 (roman2arabic "DMIM")))
  (is (= 1950 (roman2arabic "CMML")))
  (is (= 109 (roman2arabic "ILLX")))
  (is (= 349 (roman2arabic "ICLD")))
  (is (= 950 (roman2arabic "LLML")))
  (is (= 999 (roman2arabic "CIMC")))
  (is (= 45 (roman2arabic "XLVX")))
  (is (= 1850 (roman2arabic "MLCM")))
  (is (= 400 (roman2arabic "CIDI")))
  (is (= 645 (roman2arabic "DVCL")))
  (is (= 1005 (roman2arabic "XMXV")))
  (is (= 89 (roman2arabic "XILL")))
  (is (= 99 (roman2arabic "LICL")))
  (is (= 4 (roman2arabic "IIVI")))
  (is (= 55 (roman2arabic "VLVV")))
  (is (= 690 (roman2arabic "DCXC")))
  (is (= 505 (roman2arabic "IDVI")))
  (is (= 1489 (roman2arabic "IMXD")))
  (is (= 29 (roman2arabic "IXXX")))
  (is (= 1005 (roman2arabic "CMCV")))
  (is (= 1199 (roman2arabic "MCIC")))
  (is (= 1002 (roman2arabic "DDII")))
  (is (= 299 (roman2arabic "ICCC")))
  (is (= 454 (roman2arabic "LIDV")))
  (is (= 25 (roman2arabic "XXVL")))
  (is (= 155 (roman2arabic "LCCV")))
  (is (= 900 (roman2arabic "DLLD"))))

(deftest random-five-digits []
  (is (= 974 (roman2arabic "XVIXM")))
  (is (= 542 (roman2arabic "DXLII")))
  (is (= 0 (roman2arabic "MCDDC")))
  (is (= 1800 (roman2arabic "LMCLM")))
  (is (= 88 (roman2arabic "IVVIC")))
  (is (= 990 (roman2arabic "LLXMC")))
  (is (= 1445 (roman2arabic "DDVLD")))
  (is (= 648 (roman2arabic "DIICL")))
  (is (= 1490 (roman2arabic "MCDXC")))
  (is (= 1507 (roman2arabic "MDVII")))
  (is (= 1939 (roman2arabic "LMIXM")))
  (is (= 899 (roman2arabic "LIDLD")))
  (is (= 695 (roman2arabic "CCCVM")))
  (is (= 240 (roman2arabic "LCXCD")))
  (is (= 840 (roman2arabic "XDLCD")))
  (is (= 48 (roman2arabic "IMIML")))
  (is (= 330 (roman2arabic "LCXXD")))
  (is (= 954 (roman2arabic "LIMVX")))
  (is (= 1979 (roman2arabic "XIXMM")))
  (is (= 1000 (roman2arabic "VCMCV")))
  (is (= 59 (roman2arabic "CICLX")))
  (is (= 995 (roman2arabic "DVVDV")))
  (is (= 1070 (roman2arabic "XXXMC")))
  (is (= 1444 (roman2arabic "LVIMD")))
  (is (= 508 (roman2arabic "DIIVV")))
  (is (= 593 (roman2arabic "IIDVC")))
  (is (= 490 (roman2arabic "XXDVV")))
  (is (= 900 (roman2arabic "VCDDV")))
  (is (= 1054 (roman2arabic "MVILX")))
  (is (= 1580 (roman2arabic "XXMDC")))
  (is (= 1800 (roman2arabic "MLLCM")))
  (is (= 154 (roman2arabic "CVLIX")))
  (is (= 30 (roman2arabic "VXXXV")))
  (is (= 384 (roman2arabic "CIXVD")))
  (is (= 402 (roman2arabic "LLDII")))
  (is (= 895 (roman2arabic "LVLDD")))
  (is (= 450 (roman2arabic "LDVVX")))
  (is (= 2150 (roman2arabic "LMMCC")))
  (is (= 240 (roman2arabic "LXCCD")))
  (is (= 0 (roman2arabic "DXDVV")))
  (is (= 299 (roman2arabic "CCIDM")))
  (is (= 600 (roman2arabic "DXMCX")))
  (is (= 439 (roman2arabic "DILXM")))
  (is (= 970 (roman2arabic "CMLXX")))
  (is (= 449 (roman2arabic "DCMIL")))
  (is (= 185 (roman2arabic "CVLXL")))
  (is (= 849 (roman2arabic "DICLD")))
  (is (= 1401 (roman2arabic "CDDDI")))
  (is (= 399 (roman2arabic "CMIMD")))
  (is (= 1535 (roman2arabic "VXMDL"))))

(deftest random-long-number []
  (let [roman "IDDCILVCXCDMVMMCCLXIDDILMCMICIMVMCXVCMCVDLIVXCVIIXCLXXXDLMMDDVLMMLLVDVMDCLDCCXMLVXVLVIVIMVIMDMVVMCCMDICCLVLMLDMMXDCLIILICXILCXXDVDMMDVMXCVLVDMILVXMLDLMDDVDMIDLDVCLIMVLCVVLICCMXLXVLLXMICVIXVDDXDIMMDCLDVLCDIDMCLMLVMLIXDXCMMIMCDLDLMMCIDVVDLLLILIIDVIMLCLCCICMXCLIVCCDDVMIVVDVXCVXILILCDLCXIXVILDCCCIIIXLXXXVVLXDXLCXXDDCDCDIIMXIXCMXDXCCDLMXXIDCVIVVICCMDDDXLMVIVMVLMMDDMDLMDDMMVCXCCLVVCIXMLDIXDVCXVDMCMLIVCMMCMMCMXVDDLDCLILVLLVVCIDXXXVMMICDCXCXLIMLXCDMIIDCMLCXDXXLCMCLMDLLCMIDICCVXVIVDVIIVLILMDVDVXMDLXIMIICMMDMVIDMXXXMLVXILVMVCMDCIXMDVMXMXXIIVVXXLCCIXIXMDIXVILMILLLDCLVCDIMICLLILIDLIVCMLXLMDLIXIXDDLXMXDCIIIIXILMDMXCIMIXLCLCIXLLLDIDVIIVCMXVLVLIIICMLXXDCIXXDCVLXLVCIVVXDXCLCVMDILXLVMVMMXLIILLILIIMCVMXVLCLDMCCLVXLDMLILVXVCXVMDMDVMVMXMCIMVDDIMCXXMCICXVLIVXDLVXMCCXDXVDVVCVLIMIMICLVDLXCVXCMMLDCXMDVVVDDXIVMCDIMIVLXXLXXXLVILDDLILIIDVXDXXCMMLCMMCVICILMDVMLVVXIMXIXCDIMIDMLIVLVDVLCXXMLCDXDDDLMLXCXMIMDIVVXXLLXMMCVIDLDMMLCXVVMDXXDMXMXMXMDLDDIMLCDVMMVCIXDICVMXMCMXVVMLCCIXLVLLLDLXCIVIDCVDXIDCCXCMXMLDLXMIDMDMVIDMDC"]
    (is (= 1410 (roman2arabic roman)))))
